### ISSUE TITLE
[澁谷,木下]因果推論のchapterに有向分離について記載

### ISSUE THREAD

**Issue by Shibuzou** [KimuraYu45z/datascience-book#127]
グラフィカルモデルの部分には書かない
有向分離の考えをグラフィカルモデルのチャプター内では使わないため

**Comment by KimuraYu45z** [comment]
整理。

バックドア基準を厳密に書くと、

- Xからたどれる経路がない
- Xから出る矢印を除いたグラフを考えて、そのグラフの中でXとYを有向分離する


この2基準をみたす頂点はすべて(X,Y)に関してバックドア基準を満たすという

**Comment by KimuraYu45z** [comment]
このバックドア基準を厳密に説明するには有向分離の概念が必要になってくるので、説明する。



有向分離の定義も整理しておくと、

XとYを矢印の向きに関係なくつなぐすべての経路の上にある頂点があるとき、この頂点はXとYを有向分離している

**Comment by KimuraYu45z** [comment]
https://github.com/KimuraYu45z/datascience-book/issues/136
↑このissueの内容（ようするにバックドア基準を詳しく書くということ）もこのissueの内容に含めることにします
