### ISSUE TITLE
[澁谷]因果推論の章について

### ISSUE THREAD

**Issue by KimuraYu45z** [KimuraYu45z/datascience-book#130]
Judea Pearlの入門統計的因果推論
の序章を読むのが、グラフィカルモデル・ベイジアンネットワークを使った因果推論の意義を解説するのに一番良い

黒木学「構造的因果モデルの基礎」はPearl本の後追い本なので役には立つ
ただし本のレベルが少し高い

**Comment by KimuraYu45z** [comment]
@Shibuzou Judea Pearlの入門統計的因果推論
の序章を参考にした、「グラフィカルモデル・ベイジアンネットワークを使った因果推論の意義を解説」を、因果推論の章に書くのをお願いしたいです。

**Comment by Shibuzou** [comment]
\subsection
入れる位置は適宜変更
