### ISSUE TITLE
[澁谷]周辺化、加法定理

### ISSUE THREAD

**Issue by KimuraYu45z** [KimuraYu45z/datascience-book#159]
思い出した確率の周辺化、加法定理書いてない気がする

**Comment by KimuraYu45z** [comment]
ベイズの定理のところで、周辺尤度は周辺化により求めることになるので、ベイズの定理のとこに周辺化の説明書くとよさそう？

**Comment by Shibuzou** [comment]
PRML見ながら書く

**Comment by Shibuzou** [comment]
ベイズ推定の部分にベイズの定理あるのでそこに追加
