### ISSUE TITLE
参考文献

### ISSUE THREAD

**Issue by KimuraYu45z** [KimuraYu45z/datascience-book#243]
本文中にてそれっぽいところに\cite{}をつかってこれ参考にしたということを明記しておく

{}の中に入れるのはreferences.bibで定義されている名前
例は\cite{inui}

**Comment by Shibuzou** [comment]
citeしないと参考文献として載らない

**Comment by Shibuzou** [comment]
名前の姓名を逆にする

**Comment by Shibuzou** [comment]
URLのcity_keyはドメイン名

**Comment by Shibuzou** [comment]
bayesianへ修正

**Comment by Shibuzou** [comment]
参考文献の部分にwebpageのURLが表示されない問題あります
