### ISSUE TITLE
HDIに基づく検定の理解

### ISSUE THREAD

**Issue by KimuraYu45z** [KimuraYu45z/datascience-book#8]
グラフィカルモデルの枠組みで検定を統一的に扱うためには、事後分布のHDIに基づく検定を使うのでこれを理解する必要があります

木村が貼ったオライリー本のpdfに事後分布のHDI検定が書いてあるので、ちょっと目を通しておいてほしいです。
事後分布のHDIの検定のやり方は、t検定とかカイ二乗検定みたいな従来の検定よりも統一的に扱うことができます

- [ ] @tkhtmtk 
- [ ] @Shibuzou 
- [ ] @shinny-lt

**Comment by Shibuzou** [comment]
オライリーの本は『ウェブ最適化ではじめる機械学習』ってやつであってますか？

**Comment by KimuraYu45z** [comment]
あ、それです

**Comment by Shibuzou** [comment]
ありがとうございます
了解です！
